<OnboardScreen>
    MDFloatLayout:
        id:float_screen
        FitImage:
            id:fit_image
            source:'assets\images\image1.png'
        ScreenManager:
            IntroScreen:
                id:intro_screen
                name:'intro_screen'
            LoginScreen:
                id:login_screen
                name:'login_screen'
            RegisterScreen:
                id:register_screen
                name:'register_screen'
                
