<BackgroundLogin>:
    Image:
        source: 'Assets/images/background/Rectangle 1.png'
        pos_hint: {'center_x': 0.5,'center_y': 0.95}
        allow_stretch: True
    Image:
        source: 'Assets/images/background/Rectangle 2.png'
        pos_hint: {'center_x': 0.5,'center_y': 0.75}
        allow_stretch: True
    Image:
        source: 'Assets/images/background/Rectangle 3.png'
        pos_hint: {'center_x': 0.5,'center_y': 0.1}
        allow_stretch: True