#: import hex kivy.utils.get_color_from_hex
#: import md_icons kivymd.icon_definitions.md_icons
#:set blue hex('#0001FC')
#:set white hex("#FAFAFA")
#:set yellow hex("#FBDF00")
#:set red hex("#DE5246")
#:set fb_color hex("#415A93")
#: set black hex("#0A0A0A")
<RootScreen>:
    # OnboardScreen:
    #     id:onboard_screen
    #     name:'onboard_screen'
    MainScreen:
        id:main_screen
        name:'main_screen'
